# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EatSafe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


#   # Pods for EatSafe

#   target 'EatSafe-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'


pod 'RNSVG', :path => '../node_modules/react-native-svg'

pod 'RNFS', :path => '../node_modules/react-native-fs'

#   target 'EatSafeTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end

# target 'EatSafe-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for EatSafe-tvOS

#   target 'EatSafe-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTImage',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'TextDetector'
  ]
  
  pod 'Firebase/Core'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
