const allergyMap = { 
    'fish': ['anchovies', 'anchovy', 'barramundi', 'bass', 'bluefish', 'bream', 'carp', 'catfish', 'caviar', 'char', 'chub', 'cisco', 'cod', 'eel', 'fish', 'fish gelatin', 'fish oil', 'fish sticks', 'flake', 'flathead', 'flounder', 'grouper', 'haddock', 'hake', 'halibut', 'herring', 'imitation crab', 'mackerel', 'mahi mahi', 'mahi-mahi', 'marlin', 'monkfish', 'orange roughy', 'perch', 'pickerel', 'pike', 'plaice', 'pollock', 'pompano', 'porgy', 'rockfish', 'salmon', 'sardine', 'sashimi', 'scrod', 'shark', 'smelt', 'snapper', 'sole', 'surimi', 'swordfish', 'tilapia', 'trout', 'tuna', 'white fish', 'whiting'], 
    'soy': ['bean curd', 'edamame', 'endamame', 'hydrolysed plant protein', 'hydrolysed soy protein', 'hydrolysed vegetable', 'miso', 'natto', 'okara', 'protein', 'shoyu', 'soja', 'soy', 'soy albumin', 'soy bean paste', 'soy bean sprouts', 'soy cheese', 'soy fiber', 'soy flour', 'soy grits', 'soy ice cream', 'soy milk', 'soy nuts', 'soy protein', 'soy protein isolate', 'soy sauce', 'soy sprouts', 'soy yogurt', 'soya', 'soyabean', 'soybean', 'tamari', 'tempeh', 'teriyaki', 'textured vegetable', 'tofu', 'vegetable broth', 'vegetable gum', 'vegetable starch', 'yuba'],
    'diary': ['ammonium caseinate', 'brie', 'butter', 'butter acid', 'butter ester', 'butter fat', 'butter oil', 'butterfat', 'buttermilk', 'buttermilk powder', 'calcium caseinate', 'calcium lactate', 'calcium stearoyl lactylate', 'caramel', 'casein', 'casein hydrolysate', 'caseinates', 'cheese', 'chocolate', 'cocoa butter', 'condensed milk', 'cottage cheese', 'cream', 'cream cheese', 'cream of tartar', 'cultured buttermilk', 'curd', 'curds', 'custard', 'delactosed whey', 'derivative milk', 'diacetyl', 'dry milk', 'english cheddar', 'epoisses', 'evaporated milk', 'feta', 'frozen custard', 'frozen yogurt', 'gelato', 'ghee', 'goat’s milk', 'gorgonzola', 'gruyere', 'half-and-half', 'hydrolysed casein', 'hydrolysed whey', 'ice cream', 'kulfi', 'lactalbumin', 'lactalbumin phosphate', 'lactalbumin, lactalbumin phosphate', 'lactic acid', 'lacto acidophilus', 'lactoferrin', 'lactose', 'lactulose', 'lassi', 'low fat milk', 'low-fat milk', 'magnesium caseinate', 'malai', 'malted milk', 'manchego', 'margarine', 'mascarpone cheese', 'milk', 'milk protein hydrolysate', 'milkfat', 'mozzarella', 'nisin', 'non-fat milk', 'nougat', 'oleoresin', 'paneer', 'parmesan', 'parmigiano reggiano', 'potassium caseinate', 'powder milk', 'powdered milk', 'processed cheese', 'pudding', 'recaldent', 'reduced fat milk', 'rennet casein', 'ricotta', 'ricotta cheese', 'roquefort', 'royal jelly', 'skim milk', 'skimmed milk', 'sodium caseinate', 'sodium lactate', 'sodium stearoyl lactylate', 'sour cream', 'sour cream, sour cream solids', 'sour milk solids', 'sweet whey', 'tagatose', 'whey', 'whey protein hydrolysate', 'whipped cream', 'yoghurt', 'yogurt'], 
    'peanut': ['arachis oil', 'artificial nuts', 'beer nuts', 'goober nuts', 'goobers', 'ground nuts', 'groundnuts', 'lupin', 'madelonas', 'mandelonas', 'mixed nuts', 'monkey nuts', 'nu nuts', 'nut meat', 'nut pieces', 'nutmeat', 'peanut brittle', 'peanut butter', 'peanut flour', 'peanut oil', 'peanut protein', 'peanut sauce', 'peanut sprouts', 'renflakes'], 
    'gluten': ['ale', 'atta flour', 'barley', 'beer', 'bran', 'bread crumbs', 'breadcrumbs', 'bulgar', 'bulgur', 'burghul', 'cereal extract', 'club wheat', 'couscous', 'cracker meal', 'durum', 'einkorn', 'emmer', 'farina', 'farro', 'flour', 'freekeh', 'glucose syrup', 'gluten', 'gnocchi', 'graham', 'graham flour', 'grass', 'honey', 'hydrolyzed wheat protein', 'ice cream', 'kamut', 'malt', 'matzoh', 'oat', 'pasta', 'rye', 'seitan', 'semolina', 'soy sauce', 'spelt', 'sprouted wheat', 'sprouts', 'starch', 'surimi', 'tabouleh', 'triticale', 'vital wheat gluten', 'wheat', 'wheat bran', 'wheat bran hydrolysate', 'wheat germ oil', 'wheat grass', 'wheat protein isolate', 'whole wheat berries', 'yeast'], 
    'shellfish': ['abalone', 'balmain bugs', 'barnacle', 'barnacles', 'bouillabaisse', 'calamari', 'carrageenan', 'cherrystone', 'clams', 'cockle', 'crab', 'crawdad', 'crawfish', 'crayfish', 'crevette', 'crustaceans', 'cuttlefish', 'ecrevisse', 'escargot', 'fish stock', 'geoduck', 'glucosamine', 'krill', 'langouste', 'langoustine', 'lapas', 'limpet', 'littleneck', 'lobster', 'marron', 'molluscs', 'moreton bay bugs', 'mussels', 'octopus', 'opihi', 'oysters', 'panulirus', 'periwinkle', 'pismo', 'prawns', 'quahog', 'scallops', 'scampi', 'sea cucumber', 'sea snails', 'sea urchin', 'shrimp', 'snails', 'squid', 'surimi', 'tomalley', 'turban shell', 'whelk', 'yabbies'],
    'citrus': ['citrus', 'grapefruit', 'lemon', 'lime', 'oranges'],
    'legumes': ['adzuki bean', 'arhar', 'azuki bean', 'bambara groundnut', 'bengal gram', 'black gram', 'broad bean', 'butter bean', 'cajan pea', 'chickpea,', 'congo bean', 'cowitch', 'earth pea', 'field bean', 'gandules', 'garbanzo,', 'garden pea', 'golden gram', 'green gram', 'haricot bean', 'horse bean', 'hyacinth bean', 'jack bean', 'kidney bean', 'lablab', 'lentil', 'lima bean', 'lupins', 'moth bean', 'mung bean', 'navy bean', 'pigeon pea', 'pinto bean', 'protein pea', 'pulses', 'ricebean', 'scarlet runner bean', 'sword bean', 'tepary bean', 'toor', 'urad', 'velvet bean', 'vetch', 'winged bean', 'yam bean'],
    'tree nuts': ['almond', 'almond paste', 'almonds', 'artificial nuts', 'beechnut', 'black walnut', 'brazil nut', 'butternut', 'carponata', 'cashew', 'chestnut', 'chinquapin nut', 'coconut', 'filbert/hazelnut', 'gianduja', 'ginkgo nut', 'hazelnuts', 'hickory nut', 'hickory nuts', 'lichee', 'litchi', 'litchi/lichee/lychee nut', 'lychee', 'macadamia nut', 'macadamia nuts', 'marzipan', 'marzipan/almond paste', 'mashuga nuts', 'nangai nut', 'nangai nuts', 'non-gai nuts', 'pecan', 'pecans', 'pesto', 'pili nut', 'pine nut', 'pine nuts', 'pistachio', 'pistachios', 'praline', 'pralines', 'shea nut', 'tree nuts', 'walnut', 'walnuts'],
    'meat': ['bacon', 'beef', 'buffalo', 'bull', 'chicken', 'deer', 'duck', 'gelatin', 'goat', 'ham', 'lamb', 'mutton', 'ox', 'pork', 'poultry', 'salami', 'sausage', 'sausages', 'silverside', 'veal', 'venison'],
    'fruit': ['apple', 'apricots', 'artichokes', 'avocado', 'banana', 'blackberries', 'cherries', 'kiwi fruit', 'mango', 'nectarines', 'passion fruit', 'peaches', 'pear', 'pears', 'plums', 'prunes', 'raspberries', 'red wine', 'strawberries', 'watermelon', 'wine'],
    'vegetable': ['asparagus', 'bell pepper', 'carrot', 'cauliflower', 'celery', 'chilli peppers', 'cinnamon', 'coriander', 'corn', 'fennel', 'garlic', 'leek', 'mushrooms', 'onion', 'pickles', 'potato', 'saffron', 'snow peas', 'spinach', 'spring onion', 'tomatoes', 'turnip', 'zucchini'],
    'egg': ['albumen', 'albumin', 'avidin', 'binder', 'dried egg', 'dried eggs', 'egg', 'egg white', 'egg yolk', 'eggnog', 'flavoproteins', 'glaze', 'globulin', 'ice cream', 'lecithin', 'livetin', 'lysozyme', 'marshmallows', 'marzipan', 'mayonnaise', 'meringue', 'meringue mix', 'nougat', 'ovalbumin', 'ovglycoprotein', 'ovomucoid', 'ovomuxiod', 'pasta', 'powdered egg', 'surimi', 'white egg', 'yolk egg'],
    'lupin': ['lupin', 'lupin bran', 'lupin fibre', 'lupin flour', 'lupin kernel flour', 'lupine', 'lupini', 'lupini bean', 'lupinus', 'lupinus albus', 'lupinus spp'],
    'seeds': ['aqua libra', 'benne', 'benne seed', 'benniseed', 'buckwheat', 'caffeine', 'caraway', 'gingelly', 'gingelly seeds', 'gomasio', 'gomasio/sesame salt', 'halvah', 'hummus', 'kidney beans', 'mustard', 'pasteli', 'poppy seeds', 'sesame', 'sesame flour', 'sesame oil', 'sesame paste', 'sesame salt', 'sesame seed', 'sesame seeds', 'sesamol', 'sesamum indicum', 'sesarmol', 'sesemolina', 'sesomolina', 'sim sim', 'sunflower\xa0 seeds', 'tahina', 'tahini', 'tehina', 'til']
     };

export default allergyMap;